// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8XKhaNEzpjErox2L4RH6nV-eoWULxsSY',
    appId: '1:554215494194:web:2330aa308a432267cda22b',
    messagingSenderId: '554215494194',
    projectId: 'asepro-a6dac',
    authDomain: 'asepro-a6dac.firebaseapp.com',
    storageBucket: 'asepro-a6dac.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRfi3IoKAn66xVyABHWFh0K1Hq3acprP4',
    appId: '1:554215494194:android:68c7ab1bbe4f5281cda22b',
    messagingSenderId: '554215494194',
    projectId: 'asepro-a6dac',
    storageBucket: 'asepro-a6dac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNYAP3Y-05UVnibH1I3_sq0dm6D6baXvA',
    appId: '1:554215494194:ios:08487886032aa640cda22b',
    messagingSenderId: '554215494194',
    projectId: 'asepro-a6dac',
    storageBucket: 'asepro-a6dac.firebasestorage.app',
    iosBundleId: 'com.example.aseProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNYAP3Y-05UVnibH1I3_sq0dm6D6baXvA',
    appId: '1:554215494194:ios:08487886032aa640cda22b',
    messagingSenderId: '554215494194',
    projectId: 'asepro-a6dac',
    storageBucket: 'asepro-a6dac.firebasestorage.app',
    iosBundleId: 'com.example.aseProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8XKhaNEzpjErox2L4RH6nV-eoWULxsSY',
    appId: '1:554215494194:web:42c3665e90aa76d5cda22b',
    messagingSenderId: '554215494194',
    projectId: 'asepro-a6dac',
    authDomain: 'asepro-a6dac.firebaseapp.com',
    storageBucket: 'asepro-a6dac.firebasestorage.app',
  );
}
